[build]
  publish = "."
  command = ""

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/privacy/"
  to = "/privacy.html"
  status = 200

[functions]
  directory = "netlify/functions"
